import type { Metadata } from "next"
import Link from "next/link"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

export const metadata: Metadata = {
  title: "Terms of Service - LyricLingo",
  description: "Read the terms and conditions for using LyricLingo. Understand your rights and responsibilities as a user of our language learning platform.",
}

const sections = [
  {
    title: "Acceptance of Terms",
    content: [
      "By accessing or using LyricLingo, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this service.",
      "We may update these terms from time to time. Continued use of LyricLingo after changes constitutes acceptance of the new terms. We will notify you of material changes via email or in-app notification.",
    ],
  },
  {
    title: "Description of Service",
    content: [
      "LyricLingo is an AI-powered language learning platform that generates personalized songs based on your target vocabulary and learning preferences.",
      "Our service includes song generation, interactive lyrics, vocabulary tracking, progress analytics, and various learning tools designed to help you learn languages through music.",
      "Features and functionality may change over time as we improve and expand our service. We reserve the right to modify, suspend, or discontinue any aspect of the service at any time.",
    ],
  },
  {
    title: "Account Registration",
    content: [
      "To access certain features, you must create an account. You agree to provide accurate, current, and complete information during registration and to update such information as necessary.",
      "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must immediately notify us of any unauthorized use.",
      "You must be at least 13 years old to create an account. If you are under 18, you represent that you have your parent or guardian's permission to use the service.",
      "We reserve the right to suspend or terminate accounts that violate these terms or engage in fraudulent, abusive, or illegal activity.",
    ],
  },
  {
    title: "Subscription and Payments",
    content: [
      "LyricLingo offers both free and paid subscription tiers. Paid subscriptions provide access to premium features as described on our pricing page.",
      "Subscription fees are billed in advance on a monthly or annual basis. Prices are subject to change, but we will provide notice before any price increases affect your subscription.",
      "You may cancel your subscription at any time. Cancellation will take effect at the end of your current billing period. No refunds are provided for partial months.",
      "We accept payment via credit card and select cryptocurrencies. You authorize us to charge your payment method for all fees incurred.",
    ],
  },
  {
    title: "User Content and Conduct",
    content: [
      "You retain ownership of any vocabulary, preferences, or other content you provide to LyricLingo. However, by using our service, you grant us a license to use this content to provide and improve our services.",
      "You agree not to use LyricLingo to: (a) violate any laws or regulations; (b) infringe on intellectual property rights; (c) transmit harmful, offensive, or illegal content; (d) attempt to gain unauthorized access to our systems; (e) interfere with other users' enjoyment of the service.",
      "We reserve the right to remove any content or suspend accounts that violate these guidelines without prior notice.",
    ],
  },
  {
    title: "AI-Generated Content",
    content: [
      "Songs and other content generated by our AI are created for educational purposes. While we strive for accuracy and quality, AI-generated content may contain errors or inaccuracies.",
      "You may use AI-generated songs for personal, non-commercial language learning purposes. Redistribution, commercial use, or claiming AI-generated content as your own original work is prohibited.",
      "LyricLingo retains intellectual property rights to the AI systems, algorithms, and underlying technology used to generate content.",
    ],
  },
  {
    title: "Intellectual Property",
    content: [
      "LyricLingo and its original content, features, and functionality are owned by LyricLingo and are protected by international copyright, trademark, patent, and other intellectual property laws.",
      "Our trademarks, logos, and service marks may not be used in connection with any product or service without prior written consent.",
      "You may not copy, modify, distribute, sell, or lease any part of our service or included software, nor may you reverse engineer or attempt to extract the source code.",
    ],
  },
  {
    title: "Privacy",
    content: [
      "Your use of LyricLingo is also governed by our Privacy Policy, which describes how we collect, use, and protect your personal information.",
      "By using our service, you consent to the collection and use of information as described in our Privacy Policy.",
    ],
  },
  {
    title: "Disclaimers",
    content: [
      "LyricLingo is provided \"as is\" and \"as available\" without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.",
      "We do not warrant that the service will be uninterrupted, secure, or error-free, that defects will be corrected, or that the service is free of viruses or other harmful components.",
      "Language learning results may vary. We do not guarantee any specific outcomes or proficiency levels from using our service.",
    ],
  },
  {
    title: "Limitation of Liability",
    content: [
      "To the fullest extent permitted by law, LyricLingo shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill.",
      "Our total liability for any claim arising from or relating to these terms or the service shall not exceed the amount you paid to us in the twelve months preceding the claim.",
      "Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the above limitations may not apply to you.",
    ],
  },
  {
    title: "Indemnification",
    content: [
      "You agree to indemnify, defend, and hold harmless LyricLingo and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from your use of the service or violation of these terms.",
    ],
  },
  {
    title: "Governing Law and Disputes",
    content: [
      "These terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to conflict of law principles.",
      "Any disputes arising from these terms or your use of LyricLingo shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.",
      "You agree that any dispute resolution proceedings will be conducted on an individual basis and not in a class, consolidated, or representative action.",
    ],
  },
  {
    title: "General Provisions",
    content: [
      "If any provision of these terms is found to be unenforceable, the remaining provisions will continue in full force and effect.",
      "Our failure to enforce any right or provision of these terms will not constitute a waiver of such right or provision.",
      "These terms constitute the entire agreement between you and LyricLingo regarding the service and supersede any prior agreements.",
    ],
  },
  {
    title: "Contact Information",
    content: [
      "If you have any questions about these Terms of Service, please contact us at legal@lyriclingo.com.",
      "For general inquiries, you can reach us at support@lyriclingo.com or through our contact page.",
    ],
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />
      
      <main className="flex-1">
        {/* Hero */}
        <section className="relative py-16 sm:py-20 md:py-24 overflow-hidden">
          <div className="absolute inset-0 pointer-events-none">
            <div className="absolute -top-40 -left-40 w-[500px] h-[500px] rounded-full bg-coral/10 blur-3xl" />
            <div className="absolute -bottom-40 -right-40 w-[500px] h-[500px] rounded-full bg-lavender/10 blur-3xl" />
          </div>
          
          <div className="relative z-10 mx-auto max-w-4xl px-4 sm:px-6">
            <div className="text-center">
              <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-foreground tracking-tight">
                Terms of Service
              </h1>
              <p className="mt-4 text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto">
                Please read these terms carefully before using LyricLingo. By using our service, you agree to be bound by these terms.
              </p>
              <p className="mt-4 text-sm text-muted-foreground">
                Last updated: March 1, 2026
              </p>
            </div>
          </div>
        </section>

        {/* Content */}
        <section className="pb-16 sm:pb-20 md:pb-24">
          <div className="mx-auto max-w-4xl px-4 sm:px-6">
            <div className="bg-card/40 backdrop-blur-sm border border-border/50 rounded-2xl p-6 sm:p-8 md:p-10">
              <div className="prose prose-sm sm:prose-base prose-neutral dark:prose-invert max-w-none">
                <p className="text-muted-foreground leading-relaxed">
                  Welcome to LyricLingo! These Terms of Service (&quot;Terms&quot;) govern your access to and use of the LyricLingo website, applications, and services (collectively, the &quot;Service&quot;). Please read them carefully.
                </p>

                {sections.map((section, index) => (
                  <div key={index} className="mt-8 sm:mt-10">
                    <h2 className="text-lg sm:text-xl font-semibold text-foreground mb-4">
                      {index + 1}. {section.title}
                    </h2>
                    <ul className="space-y-3">
                      {section.content.map((item, itemIndex) => (
                        <li key={itemIndex} className="text-muted-foreground leading-relaxed pl-4 border-l-2 border-border">
                          {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>

              {/* Related Links */}
              <div className="mt-12 pt-8 border-t border-border/50">
                <h3 className="text-sm font-medium text-foreground mb-4">Related Pages</h3>
                <div className="flex flex-wrap gap-3">
                  <Link 
                    href="/privacy" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors px-4 py-2 rounded-lg bg-secondary/50 hover:bg-secondary"
                  >
                    Privacy Policy
                  </Link>
                  <Link 
                    href="/contact" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors px-4 py-2 rounded-lg bg-secondary/50 hover:bg-secondary"
                  >
                    Contact Us
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
